on:
  push:
    tags:
      - "**"

jobs:
  test:
    uses: OperationMonkey/shared-workflows/.github/workflows/test_and_lint.yml@main

  commitlint-config-core:
    needs: [test]
    if: ${{ startsWith(github.ref_name, 'commitlint-config-core') }}
    uses: OperationMonkey/shared-workflows/.github/workflows/publish_npm.yml@main
    secrets: inherit
    with:
      workspace: packages/commitlint-config-core

  eslint-config-core:
    needs: [test]
    if: ${{ startsWith(github.ref_name, 'eslint-config-core') }}
    uses: OperationMonkey/shared-workflows/.github/workflows/publish_npm.yml@main
    secrets: inherit
    with:
      workspace: packages/eslint-config-core

  lint-staged-config-core:
    needs: [test]
    if: ${{ startsWith(github.ref_name, 'lint-staged-config-core') }}
    uses: OperationMonkey/shared-workflows/.github/workflows/publish_npm.yml@main
    secrets: inherit
    with:
      workspace: packages/lint-staged-config-core

  node-jest-config-core:
    needs: [test]
    if: ${{ startsWith(github.ref_name, 'node-jest-config-core') }}
    uses: OperationMonkey/shared-workflows/.github/workflows/publish_npm.yml@main
    secrets: inherit
    with:
      workspace: packages/node-jest-config-core

  tsconfig-core:
    needs: [test]
    if: ${{ startsWith(github.ref_name, 'tsconfig-core') }}
    uses: OperationMonkey/shared-workflows/.github/workflows/publish_npm.yml@main
    secrets: inherit
    with:
      workspace: packages/tsconfig-core

  vite-jest-config-core:
    needs: [test]
    if: ${{ startsWith(github.ref_name, 'vite-jest-config-core') }}
    uses: OperationMonkey/shared-workflows/.github/workflows/publish_npm.yml@main
    secrets: inherit
    with:
      workspace: packages/vite-jest-config-core
